### ISSUE TITLE
Confirmation and alert modal not showing

### ISSUE THREAD

**Issue by lukejpreston** [heroku/heroku-buildpack-chrome-for-testing#28]
Hello, we are in the process of upgrading to this buildpack from the deprecated one, and we keep getting errors.

```
Capybara::ModalNotFound:
       Unable to find modal dialog
```

When we take screenshots of the rest, there are no confirmation modals. It works in the old build pack, and we are confident that the JS isn't erroring.

This is our setup with all the params we have tried.

```ruby
service = Selenium::WebDriver::Service.chrome(path: CHROMEDRIVER_PATH)

Capybara.default_driver = :ci_chrome
Capybara.javascript_driver = :ci_chrome

Capybara.register_driver :ci_chrome do |app|
  options = Selenium::WebDriver::Options.chrome
  options.binary = CHROME_BINARY_PATH
  options.add_argument('--headless')
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-gpu')
  options.add_argument('--disable-dev-shm-usage')
  options.add_argument('--window-size=2048,1200')

  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    service: service,
    options: options
  )
end
```

Nothing seems to work. We are trying to determine whether it is the new buildpack or whether our setup is invalid.

**Comment by mars** [comment]
Hi @lukejpreston,

This buildpack really just installs a up-to-date, version-aligned Chrome & Chromedriver from Google Developer's distribution site, and puts them on the executable `PATH` in dynos.

New errors in testing might be from using a different, newer version of Chrome and/or Chromedriver, compared to the previous version from the old buildpacks.

Also, ensure the selenium-webdriver gem is up-to-date in your Ruby app, because as the browser's versions march ever forward, that application-level code interface meeds to be kept current too.

I do see that the setup code sets `CHROMEDRIVER_PATH` & `CHROME_BINARY_PATH` which [are not set nor recommended in this buildpack's migration guide](https://github.com/heroku/heroku-buildpack-chrome-for-testing?tab=readme-ov-file#path-to-installed-executables).

**Comment by mars** [comment]
Closing because of no response. Also, similar to #29 & #30, in that the problematic Selenium configuration sets Chrome & Chromedriver paths to something that was not installed by this buildpack.
