### ISSUE TITLE
Chromedriver and Chrome have differing versions on Heroku

### ISSUE THREAD

**Issue by robertr2112** [heroku/heroku-buildpack-chrome-for-testing#29]
I'm running a ROR 5.2.5 app on Heroku and the Chrome for Testing buildpack stopped working last week and is still not working. I'm getting the following message in my logs:

2024-09-30T00:42:24.341535+00:00 app[web.1]: selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
2024-09-30T00:42:24.341535+00:00 app[web.1]: Current browser version is 129.0.6668.58 with binary path /app/.chrome-for-testing/chrome-linux64/chrome

And this exact problem is why this buildpack was created. I'm trying to determine what may have changed to cause the problem. I'm still on the heroku-20 stack and I'm wondering if that is the issue.

I'm also using the following ENV variable for the buildpack:

GOOGLE_CHROME_CHANNEL - Stable

I've attached the latest log with the failure and the latest build log.

[logs_0929.txt](https://github.com/user-attachments/files/17194326/logs_0929.txt)
[fbpm_build_logs.txt](https://github.com/user-attachments/files/17194329/fbpm_build_logs.txt)

**Comment by mars** [comment]
Hi @robertr2112 ,

From the build logs, I can see that the chrome-for-testing buildpack is installing Chrome + Chromedriver (v129):
```
remote:        Installed Chrome dependencies for heroku-20
remote:        Adding executables to PATH
remote:        /tmp/build_9f770f13/.chrome-for-testing/chrome-linux64/chrome
remote:        /tmp/build_9f770f13/.chrome-for-testing/chromedriver-linux64/chromedriver
remote:        Installed Chrome for Testing STABLE version 129.0.6668.58
```

I'm suspecting that your app has Chromedriver installed & configured some other way, so that it is not actually using the Chromedriver v129 installed by this buildpack.

Does your Python code set a Chromedriver path or location? Is there another config var set that would point your app to a different binary? Because [this buildpack sets the correct path](https://github.com/heroku/heroku-buildpack-chrome-for-testing?tab=readme-ov-file#path-to-installed-executables), so that the app should find Chrome & Chromedriver without additional configuration.

**Comment by Ludo915** [comment]
Hi @mars,

I have a similar problem, I removed the older chromedriver and and chrome buildpacks and added the buildpack https://github.com/heroku/heroku-buildpack-chrome-for-testing and I get the following error:

![image](https://github.com/user-attachments/assets/eb412a02-0929-4330-81aa-0c1aa28163e7)

Can you help?

**Comment by mars** [comment]
Much like #30, it is likely this issue is that other software is installing another, older version of Chromedriver.

Would love to hear confirmation @robertr2112 , but closing this stale issue.
